// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDnwHVsilbI2h9EI8oiq845b3xZWMAJPM',
    appId: '1:29651254188:web:195530f2b0f09db2e4d809',
    messagingSenderId: '29651254188',
    projectId: 'activity14-60bd1',
    authDomain: 'activity14-60bd1.firebaseapp.com',
    storageBucket: 'activity14-60bd1.firebasestorage.app',
    measurementId: 'G-PHH7DRPP2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI7ttNtAwsGeuGsbT2UMwKY02rLcQPcRU',
    appId: '1:29651254188:android:cce289d04259192ee4d809',
    messagingSenderId: '29651254188',
    projectId: 'activity14-60bd1',
    storageBucket: 'activity14-60bd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBIOzq4JoyIj_062LoOF5OPi3UsOAJ_bM',
    appId: '1:29651254188:ios:09f2de99735c68e1e4d809',
    messagingSenderId: '29651254188',
    projectId: 'activity14-60bd1',
    storageBucket: 'activity14-60bd1.firebasestorage.app',
    iosBundleId: 'com.example.activity14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBIOzq4JoyIj_062LoOF5OPi3UsOAJ_bM',
    appId: '1:29651254188:ios:09f2de99735c68e1e4d809',
    messagingSenderId: '29651254188',
    projectId: 'activity14-60bd1',
    storageBucket: 'activity14-60bd1.firebasestorage.app',
    iosBundleId: 'com.example.activity14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDnwHVsilbI2h9EI8oiq845b3xZWMAJPM',
    appId: '1:29651254188:web:411f1da722e4d52ae4d809',
    messagingSenderId: '29651254188',
    projectId: 'activity14-60bd1',
    authDomain: 'activity14-60bd1.firebaseapp.com',
    storageBucket: 'activity14-60bd1.firebasestorage.app',
    measurementId: 'G-N41CD7KBFN',
  );
}
